// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFW-E4n9o7wwGhW5v_G1kMB53Z9ginPJU',
    appId: '1:65683061758:web:65564c58041b3a2bb99eaf',
    messagingSenderId: '65683061758',
    projectId: 'foodly-full-code-flutter',
    authDomain: 'foodly-full-code-flutter.firebaseapp.com',
    storageBucket: 'foodly-full-code-flutter.appspot.com',
    measurementId: 'G-E0FYD16LTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2UmNoxbjcCjUpsTijUQL8BJSFgCHz5TI',
    appId: '1:65683061758:android:53bfc6e4d3682017b99eaf',
    messagingSenderId: '65683061758',
    projectId: 'foodly-full-code-flutter',
    storageBucket: 'foodly-full-code-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5TWMA2ZPBFMAwdwsJyFYPi5zzotPQPrQ',
    appId: '1:65683061758:ios:20eb95921061be5bb99eaf',
    messagingSenderId: '65683061758',
    projectId: 'foodly-full-code-flutter',
    storageBucket: 'foodly-full-code-flutter.appspot.com',
    androidClientId: '65683061758-3c1798541en860f40mvg7m03seo5lfs5.apps.googleusercontent.com',
    iosClientId: '65683061758-qkjp9jhargvqf8l9j1l7bsvholk1nrrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodlyDriver',
  );
}
